<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="ProgettoBalneare" duration-ms="704" started-at="2021-09-09T20:47:32Z" finished-at="2021-09-09T20:47:33Z">
    <groups>
    </groups>
    <test name="TestNG tests" duration-ms="704" started-at="2021-09-09T20:47:32Z" finished-at="2021-09-09T20:47:33Z">
      <class name="it.unica.ProgettoBalneare.Repos.UserRepoTest">
        <test-method status="PASS" signature="testAddUser()[pri:0, instance:it.unica.ProgettoBalneare.Repos.UserRepoTest@52feb982]" name="testAddUser" duration-ms="640" started-at="2021-09-09T13:47:32Z" finished-at="2021-09-09T13:47:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testGetUser()[pri:0, instance:it.unica.ProgettoBalneare.Repos.UserRepoTest@52feb982]" name="testGetUser" duration-ms="41" started-at="2021-09-09T13:47:33Z" finished-at="2021-09-09T13:47:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ok expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ok expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at it.unica.ProgettoBalneare.Repos.UserRepoTest.testGetUser(UserRepoTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUser -->
      </class> <!-- it.unica.ProgettoBalneare.Repos.UserRepoTest -->
    </test> <!-- TestNG tests -->
  </suite> <!-- ProgettoBalneare -->
</testng-results>
